server:
  port: 8080
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: POOK Midjourney API文档
    description: POOK 的Midjourney频道，实现api形式调用AI绘图
    concat: pook-guyu
    url: 
    version: v2.3
    terms-of-service-url: 
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.novicezk.midjourney.controller
